/**
 * Service data - Single Responsibility: Service catalog aggregation
 * Immutable service catalog, SEO-optimized content
 */

import type { ServiceDetail } from '../types/service';
import { SERVICE_RESIDENTIAL_REPAIR, SERVICE_RESIDENTIAL_INSTALL, SERVICE_TRACK_REPAIR, SERVICE_PANEL_REPLACEMENT } from './service-data-residential';
import { SERVICE_SPRING_REPLACEMENT, SERVICE_OPENER_REPAIR, SERVICE_CABLE_REPAIR, SERVICE_SMART_OPENERS } from './service-data-components';
import { SERVICE_COMMERCIAL_REPAIR, SERVICE_COMMERCIAL_INSTALL, SERVICE_LOADING_DOCK } from './service-data-commercial';
import { SERVICE_EMERGENCY, SERVICE_MAINTENANCE, SERVICE_INSULATION } from './service-data-specialized';

export {
  SERVICE_RESIDENTIAL_REPAIR,
  SERVICE_RESIDENTIAL_INSTALL,
  SERVICE_SPRING_REPLACEMENT,
  SERVICE_OPENER_REPAIR,
  SERVICE_TRACK_REPAIR,
  SERVICE_PANEL_REPLACEMENT,
  SERVICE_CABLE_REPAIR,
  SERVICE_COMMERCIAL_REPAIR,
  SERVICE_COMMERCIAL_INSTALL,
  SERVICE_LOADING_DOCK,
  SERVICE_EMERGENCY,
  SERVICE_MAINTENANCE,
  SERVICE_SMART_OPENERS,
  SERVICE_INSULATION,
};

export const ALL_SERVICES: readonly ServiceDetail[] = Object.freeze([
  SERVICE_RESIDENTIAL_REPAIR,
  SERVICE_RESIDENTIAL_INSTALL,
  SERVICE_SPRING_REPLACEMENT,
  SERVICE_OPENER_REPAIR,
  SERVICE_TRACK_REPAIR,
  SERVICE_PANEL_REPLACEMENT,
  SERVICE_CABLE_REPAIR,
  SERVICE_COMMERCIAL_REPAIR,
  SERVICE_COMMERCIAL_INSTALL,
  SERVICE_LOADING_DOCK,
  SERVICE_EMERGENCY,
  SERVICE_MAINTENANCE,
  SERVICE_SMART_OPENERS,
  SERVICE_INSULATION,
]);
